export const FETCH_ALL_CYCLES_METRICS = 'FETCH_ALL_CYCLES_METRICS';
export const FETCH_ALL_CYCLES_METRICS_SUCCESS = 'FETCH_ALL_CYCLES_METRICS_SUCCESS';
export const FETCH_ALL_CYCLES_METRICS_FAIL = 'FETCH_ALL_CYCLES_METRICS_FAIL';

export const FETCH_CYCLE_METRICS = 'FETCH_CYCLE_METRICS';
export const FETCH_CYCLE_METRICS_SUCCESS = 'FETCH_CYCLE_METRICS_SUCCESS';
export const FETCH_CYCLE_METRICS_FAIL = 'FETCH_CYCLE_METRICS_FAIL';

export const RESET_ERROR = 'RESET_ERROR;'

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';