export const FETCH_CYCLE_METRICS = 'FETCH_CYCLE_METRICS';
export const FETCH_CYCLE_METRICS_SUCCESS = 'FETCH_CYCLE_METRICS_SUCCESS';
export const FETCH_CYCLE_METRICS_FAIL = 'FETCH_CYCLE_METRICS_FAIL';

export const POST_CYCLE_METRICS = 'POST_CYCLE_METRICS';
export const POST_CYCLE_METRICS_SUCCESS = 'POST_CYCLE_METRICS_SUCCESS';
export const POST_CYCLE_METRICS_FAIL = 'POST_CYCLE_METRICS_FAIL';

export const RESET_ERROR = 'RESET_ERROR;'